#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

HOST = data.get("host")
#This is specific to you module, so you need to change it accordingly.

WRITABLE_PATH = data.get("WRITABLE_PATH", "/data")
MONGO_URL = data.get("MONGO_URL", "mongodb://mongo-app:27017")

# Email Settings
rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)

SMTP_HOST = smtp_settings['host']
SMTP_PORT = smtp_settings['port']
SMTP_USERNAME = smtp_settings['username']
SMTP_PASSWORD = smtp_settings['password']
SMTP_ENCRYPTION = smtp_settings['encrypt_smtp']

# MAIL_URL=smtp://user:pass@mailserver.example.com:25/
MAIL_URL = f"smtp://{SMTP_USERNAME}:{SMTP_PASSWORD}@{SMTP_HOST}:{SMTP_PORT}/"
MAIL_FROM = f'Wekan <{SMTP_USERNAME}>'

wekan_config = {
    "WRITABLE_PATH": WRITABLE_PATH,
    "MONGO_URL": MONGO_URL,
    "MAIL_URL": MAIL_URL,
    "MAIL_FROM": MAIL_FROM,
    "ROOT_URL": f"https://{HOST}",
}
agent.write_envfile("wekan.env", wekan_config)
#agent.dump_env()
