#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# Generate Password

def generate_random_password(length):
    # Generate random bytes and convert them to a hexadecimal string
    random_bytes = os.urandom(length)
    password = random_bytes.hex()
    return password[:length]

#This is specific to you module, so you need to change it accordingly.

# configure postgres db variables
POSTGRES_USER="postgres"
POSTGRES_PASSWORD=generate_random_password(16)
POSTGRES_DB="kickstart"
postgres_config = {
    "POSTGRES_USER": POSTGRES_USER,
    "POSTGRES_PASSWORD": POSTGRES_PASSWORD,
    "POSTGRES_DB": POSTGRES_DB
}
agent.write_envfile("database.env", postgres_config)
#agent.dump_env()
